### ISSUE TITLE
add_packagedirs 链接错误

### ISSUE THREAD

**Issue by lc-soft** [xmake-io/xmake-docs#10]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题

- 文档中的 add_packagedirs 链接错误，点击未跳转到正确的页面。
- 链接锚点是 targetadd_packagedirs，然而正确的锚点是 add_packagedirs。

![QQ截图20190918164142](https://user-images.githubusercontent.com/1730073/65132448-8caf5980-da33-11e9-89cc-154779535365.png)

![2019-09-18 16-41-52 的屏幕截图](https://user-images.githubusercontent.com/1730073/65132538-b49ebd00-da33-11e9-9a54-dd4908c66fc5.png)

### 期待的结果

点击后跳转到正确的页面。

### 错误信息

没有。

### 相关环境

浏览器。

### 其他信息

没有。

**Comment by waruqi** [comment]
我晚上修下 之前一次文档重构 有些link可能没完全修复

**Comment by waruqi** [comment]
我修复了。
