### ISSUE TITLE
考虑将 包依赖管理 - 使用远程包 - 添加包到仓库 移动到 API手册（描述域）- 包依赖管理

### ISSUE THREAD

**Issue by DreamOfIce** [xmake-io/xmake-docs#100]
### Is your feature request related to a problem? Please describe.

首先，目前API手册中的包依赖管理部分仍然写着敬请期待，但实际上已经在别的地方写了
其次，目前的位置有些难找，而且这种涉及API内容最好集中在一起，方便查看

### Describe the solution you'd like

移动这部分内容到API手册，并留下指向新位置链接

**Comment by waruqi** [comment]
有的，你是指哪里？

https://xmake.io/#/zh-cn/manual/global_interfaces?id=add_requires
https://xmake.io/#/zh-cn/manual/project_target?id=targetadd_packages
https://xmake.io/#/zh-cn/manual/package_instance

**Comment by DreamOfIce** [comment]
这部分：
https://xmake.io/#/zh-cn/package/remote_package?id=包描述说明
建议移动到这个位置：
https://xmake.io/#/zh-cn/manual/package_dependencies

**Comment by waruqi** [comment]
可以来个 pr

**Comment by DreamOfIce** [comment]
晚点我看看

**Comment by waruqi** [comment]
https://xmake.io/#/zh-cn/manual/package_dependencies?id=package

挪了
