### ISSUE TITLE
xmake windows通过powershell安装报错

### ISSUE THREAD

**Issue by hybcloud** [xmake-io/xmake-docs#102]
### Xmake 版本

xmake v2.7.6+master.eda07a2a7

### 操作系统版本和架构

22H2(22631.1265)

### 描述问题

当通过win11默认终端(powershell5.2)安装xmake时，即执行
```
Invoke-Expression (Invoke-Webrequest 'https://xmake.io/psget.text' -UseBasicParsing).Content
```
时，发生错误：
![_ `UCL{U_CB%O1WZ~~RU~W1](https://user-images.githubusercontent.com/43987901/221117623-d7e1bc36-dea1-4afc-ad22-54b8a5584914.jpg)
换用powershell7则正常：
![KWNRTONOPNW91P167GD9SBG](https://user-images.githubusercontent.com/43987901/221117687-128702a6-a0c4-42c3-9b02-b03f8eb9ae80.jpg)

无法解析的地方看起来像是一个三元表达式，而正好powershell7才提供三元表达式这个新特性：
![image](https://user-images.githubusercontent.com/43987901/221118266-fd0d4a7f-6c6f-408f-a8b8-acc7f129a0cd.png)

### 期待的结果

所以我觉得，要么需要在官网注明需要用powershell7来执行，要么需要把这段三元表达式改写成powershell5兼容的语法。

**Comment by waruqi** [comment]
对 powershell5 不太熟，目前也没这个环境，这个脚本也是别人贡献进来的，好改的话，可以帮忙提个 pr 过来兼容下。。

**Comment by xq114** [comment]
https://github.com/xmake-io/xmake/pull/3423 这里已经修复了
