### ISSUE TITLE
Fixed search bar position

### ISSUE THREAD

**Issue by iAndyHD3** [xmake-io/xmake-docs#104]
### Is your feature request related to a problem? Please describe.

Using the documentation page can be **frustrating** when searching for information multiple times **due to the search bar being located at the top of the sidebar.** As users scroll down to view all the results, the search bar becomes hidden and difficult to locate again, forcing them to **scroll all the way up** to the top of the sidebar. This causes inconvenience and hinders the user experience.

Furthermore, this problem is compounded by the fact that users may not even be aware of the search bar's existence in the first place. For example, when I first accessed the documentation page, I completely missed the search bar as it is not immediately apparent that it is located at the top of the sidebar. Since my intention was to scroll down to browse the site, I spent several days unaware of the search bar's existence.

### Describe the solution you'd like

To improve the user experience, it would be beneficial to have the search bar remain fixed at the top of the page Additionally, it may be helpful to make the search bar more prominent and visible to ensure that users are aware of its existence, for example by adding a search bar icon.

### Describe alternatives you've considered

not really any, fixing the search bar position should be straight forward

### Additional context

The search bar I'm referring to if it wasn't clear.
![image](https://user-images.githubusercontent.com/54410739/223426642-0cdd934b-0b3e-44b7-b9cc-881156bcc6a5.png)

**Comment by waruqi** [comment]
We use an open source documentation framework: https://github.com/docsifyjs/docsify

This is their built-in search module. But I don't know how to improve it, maybe you should open issues to docsify would be appropriate.

**Comment by iAndyHD3** [comment]
Alright thanks, I was completely unaware of this. I'll see if I can open an issue there.
