### ISSUE TITLE
Option to download pdf document

### ISSUE THREAD

**Issue by kassane** [xmake-io/xmake-docs#11]
It would be interesting and useful for consultation in an offline environment during development.

**Comment by waruqi** [comment]
You can download all markdown files and use some tools(e.g. online markdown2pdf) to convert them to pdf.

**Comment by kassane** [comment]
I used a chromium-based vscode extension called "MarkdownPDF". But it's alright!

**Comment by waruqi** [comment]
ok

**Comment by kassane** [comment]
Solution: Dash docset
[Dash User Contributions](https://github.com/Kapeli/Dash-User-Contributions/pull/2525)

**Comment by waruqi** [comment]
Great! :+1:
