### ISSUE TITLE
Add document for rules embed in package

### ISSUE THREAD

**Issue by jingkaimori** [xmake-io/xmake-docs#134]
### Is your feature request related to a problem? Please describe.

[xmake-io/xmake#2374](https://github.com/xmake-io/xmake/issues/2374) describes how to embed rules in package, but current document about this part is missing.

### Describe the solution you'd like

Fix format issues in existing document

**Comment by waruqi** [comment]
https://xmake.io/#/zh-cn/package/remote_package?id=%e5%88%86%e5%8f%91%e5%92%8c%e4%bd%bf%e7%94%a8%e8%87%aa%e5%ae%9a%e4%b9%89%e5%8c%85%e8%a7%84%e5%88%99

**Comment by waruqi** [comment]
https://xmake.io/#/package/remote_package?id=distributing-and-using-custom-package-rules

**Comment by jingkaimori** [comment]
some format issue are seen

**Comment by waruqi** [comment]
what issues? you can open a pr to improve it.
