### ISSUE TITLE
官方文档中文语言有问题

### ISSUE THREAD

**Issue by huye** [xmake-io/xmake-docs#17]
切换为中方后，搜索出来的条目地址是英文的，不知道应该报在哪里，就在这里报错了。

**Comment by waruqi** [comment]
目前用的也是docsify等第三方的文档框架，暂时我也没法改这块，你可以研究下这个repo里面的index.html配置。 不行就知道到 docsify/issues上去问他们了。

**Comment by huye** [comment]
昨天还是前天看都还好好的呢，没有动过吗，今天去看就不对了，出来的都是英文链接。

**Comment by waruqi** [comment]
没
