### ISSUE TITLE
文档中，工程目标/添加测试用例 一节有代码错误

### ISSUE THREAD

**Issue by ay-tony** [xmake-io/xmake-docs#180]
### Xmake 版本

2.9.4

### 操作系统版本和架构

Linux laptop-mach 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 GNU/Linux

### 描述问题

`工程目标/添加测试用例` 一节中，“首次测试失败就中止“标题下面附的代码错误。
[具体链接位置](https://xmake.io/#/zh-cn/manual/project_target?id=targetadd_tests)
![image](https://github.com/user-attachments/assets/ca293757-5b37-44d2-8235-e38bc8530438)
这个 `set_policy` 是用来测试失败返回0的代码（下一个标题下附带的代码，推测是打错了）。
**英文文档**对应位置也有问题。

### 期待的结果

查了下源码，应该改成
`set_policy("test.stop_on_first_failure", true)`

### 工程配置

略

### 附加信息和错误日志

略

**Comment by waruqi** [comment]
可以直接提个 pr 过来修复
