### ISSUE TITLE
document for changing package directories

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake-docs#35]
> 注：如果是`问题报障`或者`特性请求`，请选择`报告缺陷`，`特性请求`模板，否则一律不回复。

### 描述讨论详情

https://github.com/xmake-io/xmake/issues/1337

这个功能用的环境变量，在文档里面没写，要找issue才找得到，太隐蔽了

**Comment by waruqi** [comment]
嗯 东西太多，时间太少 难免有遗漏，回头有时间的时候补下

**Comment by xq114** [comment]
这个环境变量里面已经写了
