### ISSUE TITLE
document for environment variables used in xmake

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake-docs#38]
### 你在什么场景下需要该功能？

类似 https://cmake.org/cmake/help/latest/manual/cmake-env-variables.7.html

希望有一个表说明xmake中用到的环境变量（xmake-repo包用到的除外），以便查询、排错

**Comment by waruqi** [comment]
xmake show -l envs

**Comment by xq114** [comment]
> xmake show -l envs

这个表不全，只有一部分xmake程序相关的环境变量，语言相关的`CC=clang CFLAGS=--std=c++14`等用法就没有说明；（这类重在有/没有的查询而非功能描述，例如`CPPFLAGS=...`和`CUDACXX=...` xmake就并不支持）另一方面这些环境变量文档里面没有的话，需要查阅也并不方便（不能通过全局搜索搜到，而只能运行时输出，并且描述比较简单，缺少使用示例）

**Comment by waruqi** [comment]
先暂时看下这里就行了，暂时没时间整理：https://github.com/xmake-io/xmake/blob/master/xmake/toolchains/envs/xmake.lua#L28

也就这个地方和 xmake show -l envs 了。。其他地方也没啥了

**Comment by waruqi** [comment]
show 里面的我都加上了 https://xmake.io/#/zh-cn/guide/configuration?id=环境变量

还缺的 以后有时间在补充
