### ISSUE TITLE
document the uninstallation on unix-like platforms

### ISSUE THREAD

**Issue by xq114** [xmake-io/xmake-docs#49]
### 描述讨论详情
文档中没有找到在linux上怎么卸载xmake；这需要rm几个文件（xmake、xrepo），rm一个文件夹（xmake-script），复原.profile文件（删除xmake引入的一段），还比较复杂，需要一段说明

**Comment by waruqi** [comment]
这里有 https://xmake.io/#/zh-cn/guide/installation?id=%e5%8d%b8%e8%bd%bd
