### ISSUE TITLE
能否考虑整理一下该REPO的目录结构？

### ISSUE THREAD

**Issue by OpportunityLiu** [xmake-io/xmake-docs#5]
有几个问题
1. 有一些生成文件混进来了
2. 不同语言的目录层级不同，英语在根目录下，汉语却在 `zh` `cn` 两个文件夹
3. 单个文件太长，编辑困难，能否分成多个文件，在生成 html 时再进行合并

**Comment by waruqi** [comment]
> 有一些生成文件混进来了

主页面生成是执行landing/build脚本生成的，可能是会有一些其他文件

> 不同语言的目录层级不同，英语在根目录下，汉语却在 zh cn 两个文件夹

cn是里面docute文档里面路径结构，而zh是主页面的结构，用的是两个不同的框架 所以会这样


> 单个文件太长，编辑困难，能否分成多个文件，在生成 html 时再进行合并

这个暂时没办法，目前用的docute直接渲染的md文档，但是md的分割不支持，这个问题也困扰我很久了，除非换其他文档框架，比如vuepress，这就改动大了，还要修复文档里面的link，所以暂时先这么凑活着用了

**Comment by OpportunityLiu** [comment]
还是人太少了，我看vscode的插件也好久没更新了，add_cuflags都不提示的

**Comment by waruqi** [comment]
嗯 现在就我一个人维护 个人时间也不是很多 所以有些更新慢了些 vscode这个 我之前改了些 不过提交发布的时候 遇到点问题 token认证过期失效后 重新生成了 提交一直失败 后来一直没时间去折腾 

等回头我再看看

**Comment by waruqi** [comment]
vscode 的 publish 我刚重新研究了下，现在可以重新提交上去了，你可以改进下completion.ts里的提示列表，来更新下缺失的关键字  回头我会发个新版本

**Comment by waruqi** [comment]
之前有想过切到vuepress，其他都还不错，就是目录分层只能限制4层，不满足这边需求

最近看着mkdocs还不错，回头有时间研究下，如果完全满足这边需求，可以尝试下 切换到这个上 去 拆分md

**Comment by waruqi** [comment]
文档我整个替换成 docsify 框架了，所有md文档都做了拆分，尤其是manual.md，都在manual目录下

并且对外原先输出的links，我基本上都做了兼容处理，里面old目录里面放置的都是原有的老的单页文档，仅仅只是为了兼容现有links才保留的，不再做更新。

不过内部api跳转links，manual.md之前是单页面，现在拆分成多页面后，某些跨页面的 api 跳转links，我还没修复，不过这部分量不大，回头我抽空再一点点修复。。
