### ISSUE TITLE
Arch Linux 下AUR辅助工具yaourt已经停止开发，可以更新文档为新的AUR管理器

### ISSUE THREAD

**Issue by inclyc** [xmake-io/xmake-docs#52]
### 描述问题

Arch Linux 下AUR辅助工具yaourt已经[停止开发](https://github.com/archlinuxfr/yaourt)，此项目的仓库已经标注unmaintained。

### 期待的结果

更新文档为`yay -S xmake` 或其他AUR helper。

### 错误信息

不适用

### 相关环境

不适用

### 其他信息

不适用

**Comment by waruqi** [comment]
已 merge ~
