### ISSUE TITLE
xmake introduction confusing

### ISSUE THREAD

**Issue by c0nd3v** [xmake-io/xmake-docs#88]
### Xmake Version

4.7.3

### Operating System Version and Architecture

All

### Describe Bug

in the introduction it says

`Xmake ~= Make/Ninja + CMake/Meson + Vcpkg/Conan + distcc + ccache/sccache`

because xmake uses lua and in lua syntax ~= means ”is not”, this makes this line pretty confusing and I think we should remove the ~

### Expected Behavior

not confusing

**Comment by c0nd3v** [comment]
@waruqi

**Comment by waruqi** [comment]
It indicates approximate equality, but not exact equivalence.

I don't know of any other symbol to describe it.

**Comment by c0nd3v** [comment]
How about this?

≈

This has the same meaning and can’t get confused with lua syntax.

**Comment by waruqi** [comment]
done
