### ISSUE TITLE
Incorrect link in set_plat for set_arch

### ISSUE THREAD

**Issue by c0nd3v** [xmake-io/xmake-docs#89]
### Xmake Version

4.7.3

### Operating System Version and Architecture

All

### Describe Bug

![image](https://user-images.githubusercontent.com/32241825/207673848-0463138b-9222-46b9-a736-4d859bb76cb5.png)

In the set_plat description, the link to "set_arch" goes to link "project_target?id=target_setarch" but it should be "project_target?id=targetset_arch"

### Expected Behavior

Correct link

**Comment by waruqi** [comment]
I have fixed it.
