### ISSUE TITLE
Incorrect link in set_plat for set_toolchains

### ISSUE THREAD

**Issue by c0nd3v** [xmake-io/xmake-docs#90]
### Xmake Version

4.7.3

### Operating System Version and Architecture

All

### Describe Bug

![image](https://user-images.githubusercontent.com/32241825/207674865-1bbe2440-a0ec-48f8-afe6-8143b074048e.png)

In the set_plat description, the link to "set_toolchains" goes to link "project_target?id=target_settoolchains" but it should be "project_target?id=targetset_toolchains"

### Expected Behavior

Correct link

**Comment by waruqi** [comment]
I have fixed it.
